# 运行环境容器
services:
  gin_naiva_postgres:
    image: postgres:alpine
    env_file:
      - .env
    restart: on-failure
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - gin-naive-postgres-db:/var/lib/postgresql/data
    environment:
      - TZ=Asia/Shanghai
      - LANG=C.UTF-8
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  
  gingin_naiva_api:
    build: .
    restart: on-failure
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/some-api
    command: air cmd/main.go -b 0.0.0.0

volumes:
  gin-naive-postgres-db:
