# 运行环境容器
services:
  gin_naiva_mysql:
    image: mysql:8.0
    env_file:
      - .env
    restart: on-failure
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./db-data:/var/lib/mysql
    environment:
      - TZ=Asia/Shanghai
      - LANG=C.UTF-8
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  gingin_naiva_api:
    build: .
    restart: on-failure
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/some-api
    command: air cmd/main.go -b 0.0.0.0
    depends_on:
      gin_naiva_mysql:
        condition: service_healthy
