# 运行环境容器
services:
  naiva_postgres:
    image: postgres:alpine
    container_name: naiva_postgres
    env_file:
      - .env
    restart: on-failure
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - postgres-db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - TZ=Asia/Shanghai
      - LANG=C.UTF-8
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  
  gin-api:
    build: .
    container_name: naiva_api
    restart: on-failure
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/some-api
    command: air cmd/main.go -b 0.0.0.0

volumes:
  postgres-db:
